"use client"

import { Inter, Permanent_Marker } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import { Toaster } from "@/components/ui/sonner";
import UpdateProvider from "./_context/UpdateHeader";
import { PayPalScriptProvider } from "@paypal/react-paypal-js";

const inter = Inter({ subsets: ["latin"] });
const permanent = Permanent_Marker({ weight: "400", subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <PayPalScriptProvider options={{clientId:process.env.NEXT_PUBLIC_PAYPAL_CLIENT_ID}}>
      <html lang="en">
      <body className={permanent.className}>
        <UpdateProvider>
          <Header />
          {children}
          <Toaster />
        </UpdateProvider>
      </body>
    </html>
    </PayPalScriptProvider>
    
  );
}
